### ISSUE TITLE
Testing low and high dependencies

### ISSUE THREAD

**Issue by core23** [heiseonline/shariff-backend-php#102]
Sadly, the my PR was reverted :( So I wanted to start a general discussion.

IMHO only testing the composer config of the last contributor (specified in the `composer.lock` file) is a bad idea. Instead we should test the latest and lowest stable version that is currently available. This is the only way we could find bugs introduced by internal changes in external libraries we use.

I know, that there is no way to test ALL possible version, but testing the locked version wouldn't help either.
- What if the contributor didn't update his vendor libraries for a long time? We would stuck on old deps and wouldn't find bugs in newer version
- What if the contributor used a new method of an external library and didn't update the `composer.json` file? Someone who used the lowest possible version would get exceptions.

Other popular projects test the lowest and highest version too, such as symfony (https://github.com/symfony/symfony/blob/master/.travis.yml#L94)

**Comment by liayn** [comment]
> What if the contributor didn't update his vendor libraries for a long time? 
Then things would fail on his machine until he does a `composer install`

> What if the contributor used a new method of an external library...
Then he must have updated the dependency with `composer require vendor/package <version>` to have the code available. This automatically also updates the lock file, hence the commit is consistent again.
If he ommits to commit the lock file, CI will fatal because of the wrong dependency.

Testing the remote libs is simply not our job. We either have to trust those that semver is followed and no breaking changes are made, then we we can specify version ranges in the composer.json file. If we can't trust them we have to nail the specific version down to the last character.
Testing lowest and latest version still does not save us from intermediate bugs of libs.
Consider a lib we require with `^1.1` and the latest version is `1.1.9`. Our code might perfectly work with `1.1.0` and `1.1.9`, but might fail hard in versions `1.1.3 to 1.1.6` due to a bug in the lib that has been fixed meanwhile.

So my 2 cents are still. Test on CI what a dev confirmed to work locally, which usually is a single version.

**Comment by compeak** [comment]
> Test on CI what a dev confirmed to work locally, which usually is a single version.

This.
