### ISSUE TITLE
Flattr backend link does not exist anymore

### ISSUE THREAD

**Issue by ste101** [heiseonline/shariff-backend-php#182]
The link https://api.flattr.com/rest/v2/things/lookup/?url... does not work anymore

An error appears even though I'm not using flattr.

**Comment by richard67** [comment]
See also https://github.com/bradvin/social-share-urls#flattr :

> Social-share service discontinued in 2020. Attempting to use the URL results in: "404 Sorry, this page isn’t available."

So it needs a pull request (PR) to remove the Flattr service, similar as PR #159 did for LinkedIn.

If nobody else wants to make one, I can do that later.

But I don't expect much to happen with it since this repository here seems to be some kind of dead fish.

**Comment by richard67** [comment]
Pull request to remove Flattr see #190 .

**Comment by digitalgopnik** [comment]
Can be closed now since @richard67 pull-request (#190) is merged. Thank you! :pray:

**Comment by digitalgopnik** [comment]
Can be closed now since @richard67 pull-request (#190) is merged. Thank you! :pray:
